name: run and deploy to GitHub Pages

on:
    schedule:
        - cron: "0 17 * * 1-5" # At 17:00 UTC on weekdays (Monday to Friday)
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout repository content
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Python script and generate HTML
              env:
                  SOME_SECRET: ${{ secrets.SOME_SECRET }}
                  NOTIFIER_KEY: ${{ secrets.NOTIFIER_KEY }}
              run: python main.py # Certifique-se de que este script gera um arquivo index.html na pasta 'docs'

            - name: Commit generated HTML to 'docs'
              run: |
                  git config --local user.email "vicenters10@gmail.com"
                  git config --local user.name "Ryuvi"
                  git add graphs/ docs/ticker_data.json docs/images docs/
                  git diff --quiet || git commit -m "Update GitHub Pages HTML"

            - name: Push changes to main (for GitHub Pages)
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ryuvi/relatorios.git
                  git push origin main
